--------------------------------------------------------
--  File created - Sunday-September-29-2019   
--------------------------------------------------------
--------------------------------------------------------
--  DDL for Table OAUTH_ACCESS_TOKEN
--------------------------------------------------------

  CREATE TABLE "HR"."OAUTH_ACCESS_TOKEN" 
   (	"AUTHENTICATION_ID" VARCHAR2(256 BYTE), 
	"TOKEN_ID" VARCHAR2(256 BYTE), 
	"USER_NAME" VARCHAR2(256 BYTE), 
	"CLIENT_ID" VARCHAR2(256 BYTE), 
	"REFRESH_TOKEN" VARCHAR2(256 BYTE), 
	"TOKEN" BLOB, 
	"AUTHENTICATION" BLOB
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" 
 LOB ("TOKEN") STORE AS BASICFILE (
  TABLESPACE "USERS" ENABLE STORAGE IN ROW CHUNK 8192 RETENTION 
  NOCACHE LOGGING 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)) 
 LOB ("AUTHENTICATION") STORE AS BASICFILE (
  TABLESPACE "USERS" ENABLE STORAGE IN ROW CHUNK 8192 RETENTION 
  NOCACHE LOGGING 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)) ;
REM INSERTING into HR.OAUTH_ACCESS_TOKEN
SET DEFINE OFF;
Insert into HR.OAUTH_ACCESS_TOKEN (AUTHENTICATION_ID,TOKEN_ID,USER_NAME,CLIENT_ID,REFRESH_TOKEN) values ('09f1efe50c2fe116a9c2afa132f7debe','72fbeed5771547666f2be90a4e0495f6','user1@pm.com','my-client','9bd3086a3db6f2b4ac53fe012e335bde');
--------------------------------------------------------
--  DDL for Index OAUTH_ACCESS_TOKEN_PK
--------------------------------------------------------

  CREATE UNIQUE INDEX "HR"."OAUTH_ACCESS_TOKEN_PK" ON "HR"."OAUTH_ACCESS_TOKEN" ("AUTHENTICATION_ID") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" ;
--------------------------------------------------------
--  Constraints for Table OAUTH_ACCESS_TOKEN
--------------------------------------------------------

  ALTER TABLE "HR"."OAUTH_ACCESS_TOKEN" ADD CONSTRAINT "OAUTH_ACCESS_TOKEN_PK" PRIMARY KEY ("AUTHENTICATION_ID")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS"  ENABLE;
 
  ALTER TABLE "HR"."OAUTH_ACCESS_TOKEN" MODIFY ("AUTHENTICATION_ID" NOT NULL ENABLE);
